export const premiumFontFamilies = [
  { label: 'Inter', value: 'Inter, ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'DM Sans', value: '"DM Sans", ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Manrope', value: 'Manrope, ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Plus Jakarta Sans', value: '"Plus Jakarta Sans", ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Outfit', value: 'Outfit, ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Sora', value: 'Sora, ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Urbanist', value: 'Urbanist, ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Work Sans', value: '"Work Sans", ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Source Sans 3', value: '"Source Sans 3", ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Open Sans', value: '"Open Sans", ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Lato', value: 'Lato, ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Nunito Sans', value: '"Nunito Sans", ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'IBM Plex Sans', value: '"IBM Plex Sans", ui-sans-serif, system-ui, sans-serif', category: 'Modern Sans' },
  { label: 'Georgia', value: 'Georgia, "Times New Roman", serif', category: 'Editorial Serif' },
  { label: 'Merriweather', value: 'Merriweather, Georgia, serif', category: 'Editorial Serif' },
  { label: 'Lora', value: 'Lora, Georgia, serif', category: 'Editorial Serif' },
  { label: 'Noto Serif', value: '"Noto Serif", Georgia, serif', category: 'Editorial Serif' },
  { label: 'Libre Baskerville', value: '"Libre Baskerville", Georgia, serif', category: 'Editorial Serif' },
  { label: 'Playfair Display', value: '"Playfair Display", Georgia, serif', category: 'Editorial Serif' },
  { label: 'Cormorant Garamond', value: '"Cormorant Garamond", Georgia, serif', category: 'Editorial Serif' },
  { label: 'Crimson Text', value: '"Crimson Text", Georgia, serif', category: 'Editorial Serif' },
  { label: 'Roboto Slab', value: '"Roboto Slab", Georgia, serif', category: 'Editorial Serif' },
  { label: 'Fraunces', value: 'Fraunces, Georgia, serif', category: 'Editorial Serif' },
  { label: 'JetBrains Mono', value: '"JetBrains Mono", ui-monospace, monospace', category: 'Mono' },
  { label: 'Fira Code', value: '"Fira Code", ui-monospace, monospace', category: 'Mono' },
  { label: 'IBM Plex Mono', value: '"IBM Plex Mono", ui-monospace, monospace', category: 'Mono' },
  { label: 'Source Code Pro', value: '"Source Code Pro", ui-monospace, monospace', category: 'Mono' },
  { label: 'Space Mono', value: '"Space Mono", ui-monospace, monospace', category: 'Mono' },
  { label: 'System Default', value: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', category: 'System' },
];
